---

# install nginx

- name: install nginx
  apt: pkg=nginx state=present
  notify:
    - restart nginx

# copy nginx config
- name: copy nginx config
  template: src=nginx.j2 dest=/etc/nginx/sites-available/{{ project_url }}
  notify:
    - restart nginx
