---
- name: Add mariadb apt repository key
  apt_key: id=0xcbcb082a1bb943db keyserver=hkp://keyserver.ubuntu.com:80 state=present

- name: Add mariadb apt repository
  apt_repository: repo='deb http://mirror.timeweb.ru/mariadb/repo/10.1/debian wheezy main' state=present

- name: install mariadb packages
  apt: pkg=mariadb-server state=present

- name: Create MySQL user
  mysql_user: >
    name={{ mysql_user }}
    host=%
    password={{ mysql_user_password }}
    priv={{ mysql_database }}.*:ALL
    login_user={{ mysql_root_user }}
    login_password={{ mysql_root_password }}
    state=present
  notify:
    - restart mysql

# create database
- name: Create MySQL database
  mysql_db: >
    name={{ mysql_database }}
    collation=utf8_general_ci
    encoding=utf8
    login_user={{ mysql_root_user }}
    login_password={{ mysql_root_password }}
    state=present
  notify:
    - restart mysql
